import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-50 text-slate-950`}>
        <header className="w-full max-w-7xl mx-auto px-4 py-2 sm:px-8 sm:py-4 lg:px-16 lg:py-8">
          <Navbar />
        </header>
        {children}
        </body>
    </html>
  );
}
